### LOGIN

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "secret"
}

### REGISTRATION

POST http://localhost:4000/api/auth/sign-up
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "secret"
}

### FEED

GET http://localhost:4000/api/feed
Content-Type: application/javascript
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Mzg3NjQ5NTUsImlzcyI6IjUiLCJhdWQiOiJkZWZhdWx0QXVkaWVuY2UifQ.qxLJ6GUhs27vb3B9YWAYcPpFTUCF4DSywhzoMQ5Vk8o

###
